module.exports = {
  apps: [
    {
      name: "web-server",
      script: "./server/index.js",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      node_args: "--max-old-space-size=450",
      env: { NODE_ENV: "production" },
      error_file: "./logs/web-error.log",
      out_file: "./logs/web-output.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      combine_logs: true,
      time: true,
      restart_delay: 3000,
      max_restarts: 50,
      min_uptime: "5s",
      exp_backoff_restart_delay: 100,
      kill_timeout: 5000,
    },
    {
      name: "whatsapp-worker",
      script: "./worker.js",
      watch: false,
      autorestart: true,
      max_memory_restart: "800M",
      node_args: "--max-old-space-size=512",
      env: {
        NODE_ENV: "production",
        WHATSAPP_WORKER: "1",
        BOT_ISOLATION: "1",
        DYNO_TOTAL_RAM_MB: "1024",
        BOT_CHILD_HEAP_MB: "128",
        MAX_MEM_PERCENT: "80",
        RESTART_COUNT: "0"
      },
      error_file: "./logs/error.log",
      out_file: "./logs/output.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      combine_logs: true,
      time: true,
      restart_delay: 5000,
      max_restarts: 999,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      wait_ready: true,
      listen_timeout: 30000,
      kill_timeout: 8000,
    }
  ]
};
