module.exports = {
  apps: [
    {
      name: "web-server",
      script: "./server/index.js",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      node_args: "--max-old-space-size=450",
      env: { NODE_ENV: "production" },
      error_file: "./logs/web-error.log",
      out_file: "./logs/web-output.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      combine_logs: true,
      time: true,
      restart_delay: 3000,
      max_restarts: 50,
      min_uptime: "5s",
      exp_backoff_restart_delay: 100,
      kill_timeout: 5000,
    },
    {
      name: "whatsapp-worker",
      script: "./worker.js",
      watch: false,
      autorestart: true,
      max_memory_restart: "900M",
      node_args: "--max-old-space-size=768",
      env: {
        NODE_ENV: "production",
        WHATSAPP_WORKER: "1",
        BOT_ISOLATION: "1",
        DYNO_TOTAL_RAM_MB: "1024",
        BOT_CHILD_HEAP_MB: "96",
        MAX_MEM_PERCENT: "78",
        MAX_CONCURRENT_BOTS: "7",
        BOT_DISABLE_CHAT_STORE: "1",
        BOT_TURBO_ROTATION: "0",
        BOT_SYNC_INTERVAL_MS: "8000",
        BOT_ROTATION_INTERVAL_SEC: "300",
        BOT_ROTATION_SWAP_MS: "2000",
        BOT_ROTATIONS_PER_SYNC: "1",
        BOT_MIN_UPTIME_MS: "1800000",
        BOT_RESTART_HOURS: "3",
        SYNC_FULL_HISTORY: "0",
        RESTART_COUNT: "0"
      },
      error_file: "./logs/error.log",
      out_file: "./logs/output.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      combine_logs: true,
      time: true,
      restart_delay: 5000,
      max_restarts: 999,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      wait_ready: true,
      listen_timeout: 30000,
      kill_timeout: 8000,
    }
  ]
};
